### ISSUE TITLE
"user" field validation fails in mongoose while typecasting to ObjectId

### ISSUE THREAD

**Issue by feeadftth** [gitdagray/mern_stack_course#6]
### Error is in lesson_04
I encountered this error and can't get a hold of it.
This happens when trying to call a CREATE operation using POST, and it happens in the `createNewNote` function in notesController.js .
Full error log in powershell's node server instance:
`ValidationError: Note validation failed: user: Cast to ObjectId failed for value <string_value> (type string) at path "user" because of "BSONTypeError"
    at model.Document.invalidate (<path>\technotes\Sources\mern_stack_course\lesson_04\node_modules\mongoose\lib\document.js:3050:32)
    at model.$set (<path>\technotes\Sources\mern_stack_course\lesson_04\node_modules\mongoose\lib\document.js:1406:12)
    at model.$set (<path>\technotes\Sources\mern_stack_course\lesson_04\node_modules\mongoose\lib\document.js:1089:16)
    at model.Document (<path>\technotes\Sources\mern_stack_course\lesson_04\node_modules\mongoose\lib\document.js:166:12)
    at model.Model (<path>\technotes\Sources\mern_stack_course\lesson_04\node_modules\mongoose\lib\model.js:119:12)
    at new model (<path>\technotes\Sources\mern_stack_course\lesson_04\node_modules\mongoose\lib\model.js:4900:15)
    at <path>\technotes\Sources\mern_stack_course\lesson_04\node_modules\mongoose\lib\model.js:3107:22
    at <path>\technotes\Sources\mern_stack_course\lesson_04\node_modules\mongoose\lib\model.js:3143:7
    at Array.forEach (<anonymous>)
    at <path>\technotes\Sources\mern_stack_course\lesson_04\node_modules\mongoose\lib\model.js:3142:15`

I hid my personal directories under `<path>`, and the user i was trying to create the new note for under `<string_value>`.

I first encountered the error in my code, then to troubleshoot i git cloned the repo and tried again using my .env file for the DATABASE_URI variable, and got the same error.

I also triple checked that the user i was trying to assign the note to existed in the DB.

**Comment by feeadftth** [comment]
After bashing my head with this for a day, i solved it finding out it was the most stupid thing.
The `user` field sent to the `createNewNote` function in notesController.js is actually the `id` field from the database, not the actual username. Although in hindsight this was obvious, it was not specified anywhere so in case someone has the same issue:
When testing for CRUD operations, use the `id` to refer an user.
